--SELECT SUM(PONDERADO) AS PORCENTAJE_EVALUADO,[UsuarioEvaluado] FROM 
--(select MIN(PONDERADO)AS PONDERADO,[UsuarioEvaluado],[PorcentajeEvaluacionRelacion]  FROM [dbo].[EVALUACIONES$]  GROUP BY [UsuarioEvaluado],[PorcentajeEvaluacionRelacion] )
--AS PONDERADOS
--GROUP BY [UsuarioEvaluado]

--SELECT DISTINCT
--[dbo].[EVALUACIONES$].[PorcentajeEvaluacionRelacion]
--FROM 
--[dbo].[EVALUACIONES$];

--SELECT DISTINCT
--	[dbo].[EVALUACIONES$].[UsuarioEvaluado], TIPOS.PorcentajeEvaluacionRelacion
--FROM 
--[dbo].[EVALUACIONES$]
--CROSS JOIN 
--	(SELECT DISTINCT
--[dbo].[EVALUACIONES$].[PorcentajeEvaluacionRelacion]
--FROM 
--[dbo].[EVALUACIONES$]) AS TIPOS WHERE [dbo].[EVALUACIONES$].[UsuarioEvaluado]='1037607525'

--SELECT DISTINCT
--	TIPOSEVALUACION.[UsuarioEvaluado],
--	TIPOSEVALUACION.[PorcentajeEvaluacionRelacion],
--	PORCENTAJES.PONDERADO,
--	TOTALEVALUADO.PORCENTAJE_EVALUADO
--INTO #PONDERADO_REAL
--FROM 
--	(SELECT DISTINCT
--			[dbo].[EVALUACIONES$].[UsuarioEvaluado], TIPOS.PorcentajeEvaluacionRelacion
--		FROM 
--		[dbo].[EVALUACIONES$]
--		CROSS JOIN 
--			(SELECT DISTINCT
--		[dbo].[EVALUACIONES$].[PorcentajeEvaluacionRelacion]
--		FROM 
--		[dbo].[EVALUACIONES$]) AS TIPOS 
--		  ) AS TIPOSEVALUACION

--LEFT JOIN 
--	(
--		select MIN(PONDERADO)AS PONDERADO,[UsuarioEvaluado],[PorcentajeEvaluacionRelacion]  FROM [dbo].[EVALUACIONES$]  GROUP BY [UsuarioEvaluado],[PorcentajeEvaluacionRelacion] 
--	) AS PORCENTAJES
--		ON TIPOSEVALUACION.[UsuarioEvaluado] = PORCENTAJES.[UsuarioEvaluado] AND TIPOSEVALUACION.[PorcentajeEvaluacionRelacion] = PORCENTAJES.PorcentajeEvaluacionRelacion
--LEFT JOIN 
--	(
--		SELECT SUM(PONDERADO) AS PORCENTAJE_EVALUADO,[UsuarioEvaluado] FROM 
--		(select MIN(PONDERADO)AS PONDERADO,[UsuarioEvaluado],[PorcentajeEvaluacionRelacion]  FROM [dbo].[EVALUACIONES$]  GROUP BY [UsuarioEvaluado],[PorcentajeEvaluacionRelacion] )
--		AS PONDERADOS
--		GROUP BY [UsuarioEvaluado]
--	) TOTALEVALUADO
--ON	TIPOSEVALUACION.[UsuarioEvaluado] = TOTALEVALUADO.[UsuarioEvaluado] 

--ORDER BY 1,2
--SELECT * FROM #PONDERADO_REAL


--SELECT [UsuarioEvaluado],[Compañeros],[Jefe],[Equipo de trabajo],[Clientes],[Yo],PORCENTAJE_EVALUADO
--INTO #PONDERADO_AJUSTADO
--FROM #PONDERADO_REAL
--PIVOT
--	(
--		sum(PONDERADO)
--		FOR #PONDERADO_REAL.[PorcentajeEvaluacionRelacion] IN ([Compañeros],[Jefe],[Equipo de trabajo],[Clientes],[Yo])
--	) as p

--select usuarioevaluado, compañeros+jefe+[equipo de trabajo]+clientes, PORCENTAJE_EVALUADO from 
--(SELECT	
--	#PONDERADO_AJUSTADO.UsuarioEvaluado,
--	--COMPAÑEROS
--	CASE
--		--SIN COMPAÑEROS 30
--		WHEN
--			PORCENTAJE_EVALUADO<1  
--			AND Compañeros IS NULL THEN 0
--		--SIN JEFE 40
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NOT NULL
--			AND JEFE IS NULL
--			AND [Equipo de trabajo] IS NOT NULL
--			AND Clientes IS NOT NULL
--		THEN COMPAÑEROS + 0.1	
--		--SIN CLIENTES Y SIN EQUIPO 30
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NOT NULL
--			AND JEFE IS NOT NULL
--			AND [Equipo de trabajo] IS NULL
--			AND Clientes IS NULL
--		THEN COMPAÑEROS + 0.1	
--		--SIN CLIENTES Y SIN COMPAÑEROS 50
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NULL
--			AND JEFE IS NOT NULL
--			AND [Equipo de trabajo] IS NOT NULL
--			AND Clientes IS NULL
--		THEN 0	
--		--SIN CLIENTES Y SIN JEFE 60
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NOT NULL
--			AND JEFE IS NULL
--			AND [Equipo de trabajo] IS NOT NULL
--			AND Clientes IS NULL
--		THEN Compañeros + 0.30	
--		--SIN EQUIPO Y SIN COMPAÑEROS 40
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NULL
--			AND JEFE IS NOT NULL
--			AND [Equipo de trabajo] IS NULL
--			AND Clientes IS NOT NULL
--		THEN 0
--		--SIN EQUIPO Y SIN JEFE 40
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NOT NULL
--			AND JEFE IS NULL
--			AND [Equipo de trabajo] IS NULL
--			AND Clientes IS NOT NULL
--		THEN Compañeros+0.3
--		--SIN COMPAÑEROS Y SIN JEFE 70
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NULL
--			AND JEFE IS NULL
--			AND [Equipo de trabajo] IS NOT NULL
--			AND Clientes IS NOT NULL
--		THEN 0
--	ELSE Compañeros
--	END COMPAÑEROS,	
--	--JEFE
--	CASE
--		--SIN COMPAÑEROS 30
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NULL
--			AND JEFE IS NOT NULL
--			AND [Equipo de trabajo] IS NOT NULL
--			AND Clientes IS NOT NULL
--		THEN  JEFE + 0.1	
--		--SIN JEFE 40
--		WHEN 
--			JEFE IS NULL
--		THEN 0	
--		--SIN CLIENTES Y SIN EQUIPO 30
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NOT NULL
--			AND JEFE IS NOT NULL
--			AND [Equipo de trabajo] IS NULL
--			AND Clientes IS NULL
--		THEN JEFE + 0.2
--		--SIN CLIENTES Y SIN COMPAÑEROS 50
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NULL
--			AND JEFE IS NOT NULL
--			AND [Equipo de trabajo] IS NOT NULL
--			AND Clientes IS NULL
--		THEN JEFE + 0.3	
--		--SIN CLIENTES Y SIN JEFE 60
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NOT NULL
--			AND JEFE IS NULL
--			AND [Equipo de trabajo] IS NOT NULL
--			AND Clientes IS NULL
--		THEN 0	
--		--SIN EQUIPO Y SIN COMPAÑEROS 40
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NULL
--			AND JEFE IS NOT NULL
--			AND [Equipo de trabajo] IS NULL
--			AND Clientes IS NOT NULL
--		THEN JEFE + 0.2
--		--SIN EQUIPO Y SIN JEFE 50
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NOT NULL
--			AND JEFE IS NULL
--			AND [Equipo de trabajo] IS NULL
--			AND Clientes IS NOT NULL
--		THEN 0
--		--SIN COMPAÑEROS Y SIN JEFE 70
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NULL
--			AND JEFE IS NULL
--			AND [Equipo de trabajo] IS NOT NULL
--			AND Clientes IS NOT NULL
--		THEN 0
--	ELSE JEFE
--	END JEFE,
--	--EQUIPO DE TRABAJO
--	CASE
--		--SIN COMPAÑEROS 30
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NULL
--			AND JEFE IS NOT NULL
--			AND [Equipo de trabajo] IS NOT NULL
--			AND Clientes IS NOT NULL
--		THEN  [Equipo de trabajo] + 0.1	
--		--SIN JEFE 40 
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NOT NULL
--			AND JEFE IS NULL
--			AND [Equipo de trabajo] IS NOT NULL
--			AND Clientes IS NOT NULL
--		THEN  [Equipo de trabajo] + 0.2			
--		--SIN CLIENTES Y SIN EQUIPO 30
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NOT NULL
--			AND JEFE IS NOT NULL
--			AND [Equipo de trabajo] IS NULL
--			AND Clientes IS NULL
--		THEN 0
--		--SIN CLIENTES Y SIN COMPAÑEROS 50
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NULL
--			AND JEFE IS NOT NULL
--			AND [Equipo de trabajo] IS NOT NULL
--			AND Clientes IS NULL
--		THEN [Equipo de trabajo] + 0.2
--		--SIN CLIENTES Y SIN JEFE 60
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NOT NULL
--			AND JEFE IS NULL
--			AND [Equipo de trabajo] IS NOT NULL
--			AND Clientes IS NULL
--		THEN [Equipo de trabajo] + 0.3	
--		--SIN EQUIPO Y SIN COMPAÑEROS 40
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NULL
--			AND JEFE IS NOT NULL
--			AND [Equipo de trabajo] IS NULL
--			AND Clientes IS NOT NULL
--		THEN 0
--		--SIN EQUIPO Y SIN JEFE 50
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NOT NULL
--			AND JEFE IS NULL
--			AND [Equipo de trabajo] IS NULL
--			AND Clientes IS NOT NULL
--		THEN 0
--		--SIN COMPAÑEROS Y SIN JEFE 70
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NULL
--			AND JEFE IS NULL
--			AND [Equipo de trabajo] IS NOT NULL
--			AND Clientes IS NOT NULL
--		THEN [Equipo de trabajo]+0.5
--	ELSE ISNULL([Equipo de trabajo],0)
--	END [Equipo de trabajo],
--	--CLIENTES
--	CASE
--		--SIN COMPAÑEROS 30
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NULL
--			AND JEFE IS NOT NULL
--			AND [Equipo de trabajo] IS NOT NULL
--			AND Clientes IS NOT NULL
--		THEN  Clientes + 0.1	
--		--SIN JEFE 40 
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NOT NULL
--			AND JEFE IS NULL
--			AND [Equipo de trabajo] IS NOT NULL
--			AND Clientes IS NOT NULL
--		THEN  CLIENTES + 0.1			
--		--SIN CLIENTES Y SIN EQUIPO 30
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NOT NULL
--			AND JEFE IS NOT NULL
--			AND [Equipo de trabajo] IS NULL
--			AND Clientes IS NULL
--		THEN 0
--		--SIN CLIENTES Y SIN COMPAÑEROS 50
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NULL
--			AND JEFE IS NOT NULL
--			AND [Equipo de trabajo] IS NOT NULL
--			AND Clientes IS NULL
--		THEN 0
--		--SIN CLIENTES Y SIN JEFE 60
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NOT NULL
--			AND JEFE IS NULL
--			AND [Equipo de trabajo] IS NOT NULL
--			AND Clientes IS NULL
--		THEN 0	
--		--SIN EQUIPO Y SIN COMPAÑEROS 40
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NULL
--			AND JEFE IS NOT NULL
--			AND [Equipo de trabajo] IS NULL
--			AND Clientes IS NOT NULL
--		THEN Clientes+0.1
--		--SIN EQUIPO Y SIN JEFE 50
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NOT NULL
--			AND JEFE IS NULL
--			AND [Equipo de trabajo] IS NULL
--			AND Clientes IS NOT NULL
--		THEN Clientes+0.1
--		--SIN COMPAÑEROS Y SIN JEFE 70
--		WHEN 
--			PORCENTAJE_EVALUADO<1 
--			AND Compañeros IS NULL
--			AND JEFE IS NULL
--			AND [Equipo de trabajo] IS NOT NULL
--			AND Clientes IS NOT NULL
--		THEN Clientes+0.2
--	ELSE ISNULL(Clientes,0)
--	END Clientes,
--	Yo,
--	PORCENTAJE_EVALUADO
--FROM #PONDERADO_AJUSTADO)
--ajustado

--SELECT * FROM #PONDERADO_AJUSTADO

--DROP TABLE #PONDERADO_AJUSTADO;
--DROP TABLE #PONDERADO_REAL;




--CLIENTES
SELECT DISTINCT
	 [UsuarioEvaluado]	,
	 [UsuarioEvaluador],
	 PORCENTAJERELACION,
	 PONDERADO,
	 PONDERADOCALCULADO,
	 PREGUNTA
INTO #EVALUACIONCLIENTES
FROM [dbo].[EVALUACIONES$] 
WHERE [PorcentajeEvaluacionRelacion] = 'CLIENTES';

SELECT 
	 [UsuarioEvaluado],
	 MIN(PONDERADO) PONDERADOCLIENTE,
	 PREGUNTA,
	 AVG(PONDERADOCALCULADO) PROMEDIOPREGUNTACLIENTE
INTO #PROMEDIOCLIENTESPREGUNTA
FROM	
	#EVALUACIONCLIENTES
GROUP BY  
	 [UsuarioEvaluado],
	 PREGUNTA ORDER BY 1;

SELECT 
	 [UsuarioEvaluado],	 	 
	 AVG(PONDERADOCALCULADO) PROMEDIOCLIENTESGENERAL
INTO #PROMEDIOCLIENTESGENERAL
FROM	
	#EVALUACIONCLIENTES
GROUP BY  
	 [UsuarioEvaluado];

--COMPAÑEROS
SELECT DISTINCT
	 [UsuarioEvaluado]	,
	 [UsuarioEvaluador],
	 PORCENTAJERELACION,
	 PONDERADO,
	 PONDERADOCALCULADO,
	 PREGUNTA
INTO #EVALUACIONCOMPANERO
FROM [dbo].[EVALUACIONES$] 
WHERE [PorcentajeEvaluacionRelacion] = 'Compañeros';


SELECT 
	 [UsuarioEvaluado],
	 MIN(PONDERADO) PONDERADOCOMPANERO,
	 PREGUNTA,
	 AVG(PONDERADOCALCULADO) PROMEDIOPREGUNTACOMPANERO
INTO #PROMEDIOCOMPANEROPREGUNTA
FROM	
	#EVALUACIONCOMPANERO
GROUP BY  
	 [UsuarioEvaluado],
	 PREGUNTA ORDER BY 1;

SELECT 
	 [UsuarioEvaluado],	 	 
	 AVG(PONDERADOCALCULADO) PROMEDIOCOMPANEROGENERAL
INTO #PROMEDIOCOMPANEROGENERAL
FROM	
	#EVALUACIONCOMPANERO
GROUP BY  
	 [UsuarioEvaluado];

--JEFE
SELECT DISTINCT
	 [UsuarioEvaluado]	,
	 [UsuarioEvaluador],
	 PORCENTAJERELACION,
	 PONDERADO,
	 PONDERADOCALCULADO,
	 PREGUNTA
INTO #EVALUACIONJEFE
FROM [dbo].[EVALUACIONES$] 
WHERE [PorcentajeEvaluacionRelacion] = 'JEFE';

SELECT 
	 [UsuarioEvaluado],
	 MIN(PONDERADO) PONDERADOJEFE,
	 PREGUNTA,
	 AVG(PONDERADOCALCULADO) PROMEDIOPREGUNTAJEFE
INTO #PROMEDIOJEFEPREGUNTA
FROM	
	#EVALUACIONJEFE
GROUP BY  
	 [UsuarioEvaluado],
	 PREGUNTA ORDER BY 1;


SELECT 
	 [UsuarioEvaluado],	 	 
	 AVG(PONDERADOCALCULADO) PROMEDIOJEFEGENERAL
INTO #PROMEDIOJEFEGENERAL
FROM	
	#EVALUACIONJEFE
GROUP BY  
	 [UsuarioEvaluado];

--Equipo de trabajo
SELECT DISTINCT
	 [UsuarioEvaluado]	,
	 [UsuarioEvaluador],
	 PORCENTAJERELACION,
	 PONDERADO,
	 PONDERADOCALCULADO,
	 PREGUNTA
INTO #EVALUACIONEQUIPO
FROM [dbo].[EVALUACIONES$] 
WHERE [PorcentajeEvaluacionRelacion] = 'Equipo de trabajo';

SELECT 
	 [UsuarioEvaluado],
	 MIN(PONDERADO) PONDERADOEQUIPO,
	 PREGUNTA,
	 AVG(PONDERADOCALCULADO) PROMEDIOPREGUNTAEQUIPO
INTO #PROMEDIOEQUIPOPREGUNTA
FROM	
	#EVALUACIONEQUIPO
GROUP BY  
	 [UsuarioEvaluado],
	 PREGUNTA ORDER BY 1;


SELECT 
	 [UsuarioEvaluado],	 	 
	 AVG(PONDERADOCALCULADO) PROMEDIOEQUIPOGENERAL
INTO #PROMEDIOEQUIPOGENERAL
FROM	
	#EVALUACIONEQUIPO
GROUP BY  
	 [UsuarioEvaluado];



--YO
SELECT DISTINCT
	 [UsuarioEvaluado]	,
	 [UsuarioEvaluador],
	 PORCENTAJERELACION,
	 PONDERADO,
	 PONDERADOCALCULADO,
	 PREGUNTA
INTO #EVALUACIONYO
FROM [dbo].[EVALUACIONES$] 
WHERE [PorcentajeEvaluacionRelacion] = 'YO';

SELECT 
	 [UsuarioEvaluado],
	 MIN(PONDERADO) PONDERADOYO,
	 PREGUNTA,
	 AVG(PONDERADOCALCULADO) PROMEDIOPREGUNTAYO
INTO #PROMEDIOYOPREGUNTA
FROM	
	#EVALUACIONYO
GROUP BY  
	 [UsuarioEvaluado],
	 PREGUNTA ORDER BY 1;


SELECT 
	 [UsuarioEvaluado],	 	 
	 AVG(PONDERADOCALCULADO) PROMEDIOYOGENERAL
INTO #PROMEDIOYOGENERAL
FROM	
	#EVALUACIONYO
GROUP BY  
	 [UsuarioEvaluado];



SELECT 
		[UsuarioEvaluado]				AS USUARIOEVALUADO,
		[PorcentajeEvaluacionRelacion]	AS TITULO,
		Pregunta						AS PREGUNTA,
		avg([PonderadoCalculado])		AS PROMEDIO
	INTO #PROMEDIOGRUPOPREGUNTA
	FROM [dbo].[EVALUACIONES$]  
	where [UsuarioEvaluado]='1037607525'
	GROUP BY [PorcentajeEvaluacionRelacion], [UsuarioEvaluado], Pregunta


--SELECT 
--	USUARIOEVALUADO,
--	PREGUNTA,
--	SUM(PROMEDIO) AS TOTALPREGUNTA
--FROM 
--	#PROMEDIOGRUPOPREGUNTA
--GROUP BY 
--	USUARIOEVALUADO,PREGUNTA

SELECT 
	[EVALUACIONES$].[UsuarioEvaluado],
	[NombreEvaluado],
	[EVALUACIONES$].[Pregunta],	
	[EVALUACIONES$].[UsuarioEvaluador],
	CASE 
		WHEN #EVALUACIONCLIENTES.[UsuarioEvaluador] IS NOT NULL THEN 'CLIENTE' 
		WHEN #EVALUACIONCOMPANERO.[UsuarioEvaluador] IS NOT NULL THEN 'COMPAÑERO' 
		WHEN #EVALUACIONJEFE.[UsuarioEvaluador] IS NOT NULL THEN 'JEFE' 
		WHEN #EVALUACIONEQUIPO.[UsuarioEvaluador] IS NOT NULL THEN 'EQUIPO'
		WHEN #EVALUACIONYO.[UsuarioEvaluador] IS NOT NULL THEN 'YO'
	END AS TIPOEVALUADOR,
	--CLIENTES	
	#EVALUACIONCLIENTES.PORCENTAJERELACION				EVALUACIONCLIENTE,
	#PROMEDIOCLIENTESPREGUNTA.PONDERADOCLIENTE			PONDERADOCLIENTE,
	#EVALUACIONCLIENTES.PONDERADOCALCULADO				PONDERADOCALCULADOCLIENTE,
	#PROMEDIOCLIENTESPREGUNTA.PROMEDIOPREGUNTACLIENTE	PROMEDIOPREGUNTACLIENTE,
	#PROMEDIOCLIENTESGENERAL.PROMEDIOCLIENTESGENERAL	PROMEDIOCLIENTESGENERAL,
	--COMPAÑEROS
	#EVALUACIONCOMPANERO.PORCENTAJERELACION					EVALUACIONCOMPAÑERO,
	#PROMEDIOCOMPANEROPREGUNTA.PONDERADOCOMPANERO			PONDERADOCOMPANERO,
	#EVALUACIONCOMPANERO.PONDERADOCALCULADO					PONDERADOCALCULADOCOMPAÑERO,
	#PROMEDIOCOMPANEROPREGUNTA.PROMEDIOPREGUNTACOMPANERO	PROMEDIOPREGUNTACOMPANERO,
	#PROMEDIOCOMPANEROGENERAL.PROMEDIOCOMPANEROGENERAL		PROMEDIOCOMPANEROGENERAL,
	--JEFE
	#EVALUACIONJEFE.PORCENTAJERELACION						EVALUACIONJEFE,
	#PROMEDIOJEFEPREGUNTA.PONDERADOJEFE						PONDERADOJEFE,
	#EVALUACIONJEFE.PONDERADOCALCULADO						PONDERADOCALCULADOJEFE,
	#PROMEDIOJEFEPREGUNTA.PROMEDIOPREGUNTAJEFE				PROMEDIOPREGUNTAJEFE,
	#PROMEDIOJEFEGENERAL.PROMEDIOJEFEGENERAL				PROMEDIOJEFEGENERAL,
	--EQUIPO
	#EVALUACIONEQUIPO.PORCENTAJERELACION					EVALUACIONEQUIPO,
	#PROMEDIOEQUIPOPREGUNTA.PONDERADOEQUIPO					PONDERADOEQUIPO,
	#EVALUACIONEQUIPO.PONDERADOCALCULADO					PONDERADOCALCULADOEQUIPO,
	#PROMEDIOEQUIPOPREGUNTA.PROMEDIOPREGUNTAEQUIPO			PROMEDIOPREGUNTAEQUIPO,
	#PROMEDIOEQUIPOGENERAL.PROMEDIOEQUIPOGENERAL			PROMEDIOEQUIPOGENERAL,
	--YO
	#EVALUACIONYO.PORCENTAJERELACION						EVALUACIONYO,
	#PROMEDIOYOPREGUNTA.PONDERADOYO							PONDERADOYO,
	#EVALUACIONYO.PONDERADOCALCULADO						PONDERADOCALCULADOYO,
	#PROMEDIOYOPREGUNTA.PROMEDIOPREGUNTAYO					PROMEDIOPREGUNTAYO,
	#PROMEDIOYOGENERAL.PROMEDIOYOGENERAL					PROMEDIOYOGENERAL,
	--EVALACIONPREGUNTA
	ISNULL(#PROMEDIOCLIENTESPREGUNTA.PROMEDIOPREGUNTACLIENTE,0)+ISNULL(#PROMEDIOCOMPANEROPREGUNTA.PROMEDIOPREGUNTACOMPANERO,0)+ISNULL(#PROMEDIOJEFEPREGUNTA.PROMEDIOPREGUNTAJEFE,0)+ISNULL(#PROMEDIOEQUIPOPREGUNTA.PROMEDIOPREGUNTAEQUIPO,0)+ISNULL(#PROMEDIOYOPREGUNTA.PROMEDIOPREGUNTAYO,0) AS EVALUACIONPREGUNTA,
	--EVALUACION GENERAL
	(isnull(#PROMEDIOCLIENTESGENERAL.PROMEDIOCLIENTESGENERAL,0)+isnull(#PROMEDIOCOMPANEROGENERAL.PROMEDIOCOMPANEROGENERAL,0)+isnull(#PROMEDIOJEFEGENERAL.PROMEDIOJEFEGENERAL,0)+isnull(#PROMEDIOEQUIPOGENERAL.PROMEDIOEQUIPOGENERAL,0)+isnull(#PROMEDIOYOGENERAL.PROMEDIOYOGENERAL,0))*100 AS EVALUACIONGENERAL,
	--PORCENTAJE EVALUADO
	(isnull(#PROMEDIOCLIENTESPREGUNTA.PONDERADOCLIENTE,0)+isnull(#PROMEDIOCOMPANEROPREGUNTA.PONDERADOCOMPANERO,0)+isnull(#PROMEDIOJEFEPREGUNTA.PONDERADOJEFE,0)+isnull(#PROMEDIOEQUIPOPREGUNTA.PONDERADOEQUIPO,0)+isnull(#PROMEDIOYOPREGUNTA.PONDERADOYO,0)) *100 AS PORCENTAJEEVALUADO,
	((isnull(#PROMEDIOCLIENTESPREGUNTA.PONDERADOCLIENTE,0)+isnull(#PROMEDIOCOMPANEROPREGUNTA.PONDERADOCOMPANERO,0)+isnull(#PROMEDIOJEFEPREGUNTA.PONDERADOJEFE,0)+isnull(#PROMEDIOEQUIPOPREGUNTA.PONDERADOEQUIPO,0)+isnull(#PROMEDIOYOPREGUNTA.PONDERADOYO,0)) *100)-
	((isnull(#PROMEDIOCLIENTESGENERAL.PROMEDIOCLIENTESGENERAL,0)+isnull(#PROMEDIOCOMPANEROGENERAL.PROMEDIOCOMPANEROGENERAL,0)+isnull(#PROMEDIOJEFEGENERAL.PROMEDIOJEFEGENERAL,0)+isnull(#PROMEDIOEQUIPOGENERAL.PROMEDIOEQUIPOGENERAL,0)+isnull(#PROMEDIOYOGENERAL.PROMEDIOYOGENERAL,0))*100) AS DIFERENCIA
FROM 
	[dbo].[EVALUACIONES$]
	--CLIENTES
	LEFT JOIN #EVALUACIONCLIENTES ON [dbo].[EVALUACIONES$].[UsuarioEvaluado] = #EVALUACIONCLIENTES.usuarioevaluado 
				and [EVALUACIONES$].pregunta = #EVALUACIONCLIENTES.pregunta
				and [EVALUACIONES$].[UsuarioEvaluador] = #EVALUACIONCLIENTES.[UsuarioEvaluador]
				and #EVALUACIONCLIENTES.PorcentajeRelacion = [EVALUACIONES$].PorcentajeRelacion
	LEFT JOIN #PROMEDIOCLIENTESPREGUNTA ON  [dbo].[EVALUACIONES$].[UsuarioEvaluado] = #PROMEDIOCLIENTESPREGUNTA.usuarioevaluado 
				and [EVALUACIONES$].pregunta = #PROMEDIOCLIENTESPREGUNTA.pregunta
	LEFT JOIN #PROMEDIOCLIENTESGENERAL ON  [dbo].[EVALUACIONES$].[UsuarioEvaluado] = #PROMEDIOCLIENTESGENERAL.usuarioevaluado 
	--COMPAÑEROS
	LEFT JOIN #EVALUACIONCOMPANERO ON [dbo].[EVALUACIONES$].[UsuarioEvaluado] = #EVALUACIONCOMPANERO.usuarioevaluado 
				and [EVALUACIONES$].pregunta = #EVALUACIONCOMPANERO.pregunta
				and [EVALUACIONES$].[UsuarioEvaluador] = #EVALUACIONCOMPANERO.[UsuarioEvaluador]
	LEFT JOIN #PROMEDIOCOMPANEROPREGUNTA ON  [dbo].[EVALUACIONES$].[UsuarioEvaluado] = #PROMEDIOCOMPANEROPREGUNTA.usuarioevaluado 
				and [EVALUACIONES$].pregunta = #PROMEDIOCOMPANEROPREGUNTA.pregunta
	LEFT JOIN #PROMEDIOCOMPANEROGENERAL ON  [dbo].[EVALUACIONES$].[UsuarioEvaluado] = #PROMEDIOCOMPANEROGENERAL.usuarioevaluado 
	--JEFE
	LEFT JOIN #EVALUACIONJEFE ON [dbo].[EVALUACIONES$].[UsuarioEvaluado] = #EVALUACIONJEFE.usuarioevaluado 
				and [EVALUACIONES$].pregunta = #EVALUACIONJEFE.pregunta
				and [EVALUACIONES$].[UsuarioEvaluador] = #EVALUACIONJEFE.[UsuarioEvaluador]
	LEFT JOIN #PROMEDIOJEFEPREGUNTA ON  [dbo].[EVALUACIONES$].[UsuarioEvaluado] = #PROMEDIOJEFEPREGUNTA.usuarioevaluado 
				and [EVALUACIONES$].pregunta = #PROMEDIOJEFEPREGUNTA.pregunta
	LEFT JOIN #PROMEDIOJEFEGENERAL ON  [dbo].[EVALUACIONES$].[UsuarioEvaluado] = #PROMEDIOJEFEGENERAL.usuarioevaluado 
	--EQUIPO
	LEFT JOIN #EVALUACIONEQUIPO ON [dbo].[EVALUACIONES$].[UsuarioEvaluado] = #EVALUACIONEQUIPO.usuarioevaluado 
				and [EVALUACIONES$].pregunta = #EVALUACIONEQUIPO.pregunta
				and [EVALUACIONES$].[UsuarioEvaluador] = #EVALUACIONEQUIPO.[UsuarioEvaluador]
	LEFT JOIN #PROMEDIOEQUIPOPREGUNTA ON  [dbo].[EVALUACIONES$].[UsuarioEvaluado] = #PROMEDIOEQUIPOPREGUNTA.usuarioevaluado 
				and [EVALUACIONES$].pregunta = #PROMEDIOEQUIPOPREGUNTA.pregunta
	LEFT JOIN #PROMEDIOEQUIPOGENERAL ON  [dbo].[EVALUACIONES$].[UsuarioEvaluado] = #PROMEDIOEQUIPOGENERAL.usuarioevaluado 
	--YO
	LEFT JOIN #EVALUACIONYO ON [dbo].[EVALUACIONES$].[UsuarioEvaluado] = #EVALUACIONYO.usuarioevaluado 
				and [EVALUACIONES$].pregunta = #EVALUACIONYO.pregunta
				and [EVALUACIONES$].[UsuarioEvaluador] = #EVALUACIONYO.[UsuarioEvaluador]
	LEFT JOIN #PROMEDIOYOPREGUNTA ON  [dbo].[EVALUACIONES$].[UsuarioEvaluado] = #PROMEDIOYOPREGUNTA.usuarioevaluado 
				and [EVALUACIONES$].pregunta = #PROMEDIOYOPREGUNTA.pregunta
	LEFT JOIN #PROMEDIOYOGENERAL ON  [dbo].[EVALUACIONES$].[UsuarioEvaluado] = #PROMEDIOYOGENERAL.usuarioevaluado 
--WHERE [EVALUACIONES$].[UsuarioEvaluado]='1017193899'
--WHERE [EVALUACIONES$].[UsuarioEvaluado]='1036650001'
--WHERE [EVALUACIONES$].[UsuarioEvaluado]='1037607525'


order by 1,3,5

DROP TABLE #PROMEDIOGRUPOPREGUNTA;
DROP TABLE #EVALUACIONCLIENTES;
DROP TABLE #PROMEDIOCLIENTESPREGUNTA;
DROP TABLE #PROMEDIOCLIENTESGENERAL;
DROP TABLE #EVALUACIONCOMPANERO;
DROP TABLE #PROMEDIOCOMPANEROPREGUNTA;
DROP TABLE #PROMEDIOCOMPANEROGENERAL;
DROP TABLE #EVALUACIONJEFE;
DROP TABLE #PROMEDIOJEFEPREGUNTA;
DROP TABLE #PROMEDIOJEFEGENERAL;
DROP TABLE #EVALUACIONYO;
DROP TABLE #PROMEDIOYOPREGUNTA;
DROP TABLE #PROMEDIOYOGENERAL;
DROP TABLE #EVALUACIONEQUIPO;
DROP TABLE #PROMEDIOEQUIPOPREGUNTA;
DROP TABLE #PROMEDIOEQUIPOGENERAL;




